# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FlintCMS
email: jasonetco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  FlintCMS is a super-speedy, content-focused Node.js Content Management
  System with a clear templating API and tons of other features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flintcms.co" # the base hostname & protocol for your site
github_repo: https://github.com/JasonEtco/flintcms
docs-github_repo: https://github.com/JasonEtco/flintcms-site
twitter_username: jasonetco
github_username:  jasonetco
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - node_modules
  - README.md

collections:
  docs:
    permalink: docs/:title/
    output: true

# Build settings
markdown: kramdown
